# Tratamento de Dados - ENEM 2020
Carregamento, dicionário de variáveis, tipagem e renomeação de colunas.

In [1]:
import pandas as pd

DADOS_PATH = r'..\data\raw\microdados_enem_2020\DADOS\MICRODADOS_ENEM_2020.csv'
DICIONARIO_PATH = r'..\data\raw\microdados_enem_2020\DICIONÁRIO\Dicionário_Microdados_Enem_2020.xlsx'

## 1. Dicionário de variáveis

In [5]:
xl = pd.ExcelFile(DICIONARIO_PATH)
print('Abas disponíveis:', xl.sheet_names)

Abas disponíveis: ['MICRODADOS_ENEM_2020', 'ITENS_PROVA_2020']

In [7]:
# Estrutura da primeria aba do dicionário
df_dic_raw = xl.parse(xl.sheet_names[0])
print(df_dic_raw.shape)
df_dic_raw.head(10)

(362, 6)

,DICIONÁRIO DE VARIÁVEIS - ENEM 2020,Unnamed: 1,Unnamed: 2,Unnamed: 3,Unnamed: 4,Unnamed: 5
0,NaN,NaN,NaN,NaN,NaN,NaN
1,NOME DA VARIÁVEL,Descrição,Variáveis Categóricas,NaN,Tamanho,Tipo
2,NaN,NaN,Categoria,Descrição,NaN,NaN
3,DADOS DO PARTICIPANTE,NaN,NaN,NaN,NaN,NaN
4,NU_INSCRICAO,Número de inscrição1,NaN,NaN,12,Numérica
5,NU_ANO,Ano do Enem,NaN,NaN,4,Numérica
6,TP_FAIXA_ETARIA,Faixa etária2,1,Menor de 17 anos,2,Numérica
7,NaN,NaN,2,17 anos,NaN,NaN
8,NaN,NaN,3,18 anos,NaN,NaN
9,NaN,NaN,4,19 anos,NaN,NaN

In [12]:
# Mapeamento a partir do dicionário oficial do ENEM 2020
# Coluna original -> Nome legível (possível de ser identificado sem consultar o dicionário)
rename_map = {
    'NU_INSCRICAO':          'Numero_Inscricao',
    'NU_ANO':                'Ano',
    'TP_FAIXA_ETARIA':       'Faixa_Etaria',
    'TP_SEXO':               'Sexo',
    'TP_ESTADO_CIVIL':       'Estado_Civil',
    'TP_COR_RACA':           'Cor_Raca',
    'TP_NACIONALIDADE':      'Nacionalidade',
    'TP_ST_CONCLUSAO':       'Situacao_Conclusao_EM',
    'TP_ANO_CONCLUIU':       'Ano_Conclusao_EM',
    'TP_ESCOLA':             'Tipo_Escola',
    'TP_ENSINO':             'Tipo_Ensino',
    'IN_TREINEIRO':          'Treineiro',
    'CO_MUNICIPIO_ESC':      'Cod_Municipio_Escola',
    'NO_MUNICIPIO_ESC':      'Nome_Municipio_Escola',
    'CO_UF_ESC':             'Cod_UF_Escola',
    'SG_UF_ESC':             'UF_Escola',
    'TP_DEPENDENCIA_ADM_ESC':'Dependencia_Adm_Escola',
    'TP_LOCALIZACAO_ESC':    'Localizacao_Escola',
    'TP_SIT_FUNC_ESC':       'Situacao_Funcionamento_Escola',
    'CO_MUNICIPIO_PROVA':    'Cod_Municipio_Prova',
    'NO_MUNICIPIO_PROVA':    'Nome_Municipio_Prova',
    'CO_UF_PROVA':           'Cod_UF_Prova',
    'SG_UF_PROVA':           'UF_Prova',
    'TP_PRESENCA_CN':        'Presenca_Ciencias_Natureza',
    'TP_PRESENCA_CH':        'Presenca_Ciencias_Humanas',
    'TP_PRESENCA_LC':        'Presenca_Linguagens',
    'TP_PRESENCA_MT':        'Presenca_Matematica',
    'CO_PROVA_CN':           'Cod_Prova_Ciencias_Natureza',
    'CO_PROVA_CH':           'Cod_Prova_Ciencias_Humanas',
    'CO_PROVA_LC':           'Cod_Prova_Linguagens',
    'CO_PROVA_MT':           'Cod_Prova_Matematica',
    'NU_NOTA_CN':            'Nota_Ciencias_Natureza',
    'NU_NOTA_CH':            'Nota_Ciencias_Humanas',
    'NU_NOTA_LC':            'Nota_Linguagens',
    'NU_NOTA_MT':            'Nota_Matematica',
    'TX_RESPOSTAS_CN':       'Respostas_Ciencias_Natureza',
    'TX_RESPOSTAS_CH':       'Respostas_Ciencias_Humanas',
    'TX_RESPOSTAS_LC':       'Respostas_Linguagens',
    'TX_RESPOSTAS_MT':       'Respostas_Matematica',
    'TP_LINGUA':             'Lingua_Estrangeira',
    'TX_GABARITO_CN':        'Gabarito_Ciencias_Natureza',
    'TX_GABARITO_CH':        'Gabarito_Ciencias_Humanas',
    'TX_GABARITO_LC':        'Gabarito_Linguagens',
    'TX_GABARITO_MT':        'Gabarito_Matematica',
    'TP_STATUS_REDACAO':     'Status_Redacao',
    'NU_NOTA_COMP1':         'Nota_Redacao_Comp1',
    'NU_NOTA_COMP2':         'Nota_Redacao_Comp2',
    'NU_NOTA_COMP3':         'Nota_Redacao_Comp3',
    'NU_NOTA_COMP4':         'Nota_Redacao_Comp4',
    'NU_NOTA_COMP5':         'Nota_Redacao_Comp5',
    'NU_NOTA_REDACAO':       'Nota_Redacao',
    'Q001': 'Q01_Escolaridade_Pai',
    'Q002': 'Q02_Escolaridade_Mae',
    'Q003': 'Q03_Ocupacao_Pai',
    'Q004': 'Q04_Ocupacao_Mae',
    'Q005': 'Q05_Pessoas_Residencia',
    'Q006': 'Q06_Renda_Familiar',
    'Q007': 'Q07_Empregado_Domestico',
    'Q008': 'Q08_Banheiro',
    'Q009': 'Q09_Quarto',
    'Q010': 'Q10_Carro',
    'Q011': 'Q11_Moto',
    'Q012': 'Q12_Geladeira',
    'Q013': 'Q13_Freezer',
    'Q014': 'Q14_Maquina_Lavar',
    'Q015': 'Q15_Maquina_Secar',
    'Q016': 'Q16_Micro_Ondas',
    'Q017': 'Q17_Maquina_Lavar_Louca',
    'Q018': 'Q18_Aspirador_Po',
    'Q019': 'Q19_TV_Cores',
    'Q020': 'Q20_DVD',
    'Q021': 'Q21_TV_Assinatura',
    'Q022': 'Q22_Telefone_Fixo',
    'Q023': 'Q23_Computador',
    'Q024': 'Q24_Internet',
    'Q025': 'Q25_Celular',
}

# Visualização do dicionário como tabela
df_dicionario = pd.DataFrame(
    [(orig, novo) for orig, novo in rename_map.items()],
    columns=['Coluna Original', 'Nome Legível']
)
df_dicionario

    Coluna Original       Nome Legível
0      NU_INSCRICAO   Numero_Inscricao
1            NU_ANO                Ano
2   TP_FAIXA_ETARIA       Faixa_Etaria
3           TP_SEXO               Sexo
4   TP_ESTADO_CIVIL       Estado_Civil
..              ...                ...
71             Q021  Q21_TV_Assinatura
72             Q022  Q22_Telefone_Fixo
73             Q023     Q23_Computador
74             Q024       Q24_Internet
75             Q025        Q25_Celular

[76 rows x 2 columns]

## 2. Carregamento dos dados

In [14]:
dtype_map = {
    'NU_INSCRICAO': str,
    'NU_ANO': 'int16',
    'TP_FAIXA_ETARIA': 'Int8', 'TP_SEXO': str, 'TP_ESTADO_CIVIL': 'Int8',
    'TP_COR_RACA': 'Int8', 'TP_NACIONALIDADE': 'Int8', 'TP_ST_CONCLUSAO': 'Int8',
    'TP_ANO_CONCLUIU': 'Int8', 'TP_ESCOLA': 'Int8', 'TP_ENSINO': 'Int8',
    'IN_TREINEIRO': 'Int8',
    'CO_MUNICIPIO_ESC': 'Int32', 'NO_MUNICIPIO_ESC': str,
    'CO_UF_ESC': 'Int8', 'SG_UF_ESC': str,
    'TP_DEPENDENCIA_ADM_ESC': 'Int8', 'TP_LOCALIZACAO_ESC': 'Int8', 'TP_SIT_FUNC_ESC': 'Int8',
    'CO_MUNICIPIO_PROVA': 'Int32', 'NO_MUNICIPIO_PROVA': str,
    'CO_UF_PROVA': 'Int8', 'SG_UF_PROVA': str,
    'TP_PRESENCA_CN': 'Int8', 'TP_PRESENCA_CH': 'Int8',
    'TP_PRESENCA_LC': 'Int8', 'TP_PRESENCA_MT': 'Int8',
    'NU_NOTA_CN': 'float32', 'NU_NOTA_CH': 'float32',
    'NU_NOTA_LC': 'float32', 'NU_NOTA_MT': 'float32',
    'TP_LINGUA': 'Int8', 'TP_STATUS_REDACAO': 'Int8',
    'NU_NOTA_COMP1': 'Int16', 'NU_NOTA_COMP2': 'Int16',
    'NU_NOTA_COMP3': 'Int16', 'NU_NOTA_COMP4': 'Int16',
    'NU_NOTA_COMP5': 'Int16', 'NU_NOTA_REDACAO': 'float32',
}

df = pd.read_csv(
    DADOS_PATH,
    sep=';',
    encoding='latin-1',
    usecols=list(rename_map.keys()),
    dtype=dtype_map,
)
print(f'Shape original: {df.shape}')
print(f'Colunas: {df.columns.tolist()}')

Shape original: (5783109, 76)
Colunas: ['NU_INSCRICAO', 'NU_ANO', 'TP_FAIXA_ETARIA', 'TP_SEXO', 'TP_ESTADO_CIVIL', 'TP_COR_RACA', 'TP_NACIONALIDADE', 'TP_ST_CONCLUSAO', 'TP_ANO_CONCLUIU', 'TP_ESCOLA', 'TP_ENSINO', 'IN_TREINEIRO', 'CO_MUNICIPIO_ESC', 'NO_MUNICIPIO_ESC', 'CO_UF_ESC', 'SG_UF_ESC', 'TP_DEPENDENCIA_ADM_ESC', 'TP_LOCALIZACAO_ESC', 'TP_SIT_FUNC_ESC', 'CO_MUNICIPIO_PROVA', 'NO_MUNICIPIO_PROVA', 'CO_UF_PROVA', 'SG_UF_PROVA', 'TP_PRESENCA_CN', 'TP_PRESENCA_CH', 'TP_PRESENCA_LC', 'TP_PRESENCA_MT', 'CO_PROVA_CN', 'CO_PROVA_CH', 'CO_PROVA_LC', 'CO_PROVA_MT', 'NU_NOTA_CN', 'NU_NOTA_CH', 'NU_NOTA_LC', 'NU_NOTA_MT', 'TX_RESPOSTAS_CN', 'TX_RESPOSTAS_CH', 'TX_RESPOSTAS_LC', 'TX_RESPOSTAS_MT', 'TP_LINGUA', 'TX_GABARITO_CN', 'TX_GABARITO_CH', 'TX_GABARITO_LC', 'TX_GABARITO_MT', 'TP_STATUS_REDACAO', 'NU_NOTA_COMP1', 'NU_NOTA_COMP2', 'NU_NOTA_COMP3', 'NU_NOTA_COMP4', 'NU_NOTA_COMP5', 'NU_NOTA_REDACAO', 'Q001', 'Q002', 'Q003', 'Q004', 'Q005', 'Q006', 'Q007', 'Q008', 'Q009', 'Q010', 'Q011', 'Q012', 'Q013', 'Q014', 'Q015', 'Q016', 'Q017', 'Q018', 'Q019', 'Q020', 'Q021', 'Q022', 'Q023', 'Q024', 'Q025']

## 3. Renomeação das colunas

In [15]:
df = df.rename(columns=rename_map)
print(f'Shape após renomeação: {df.shape}')
print(f'Novas colunas: {df.columns.tolist()}')

Shape após renomeação: (5783109, 76)
Novas colunas: ['Numero_Inscricao', 'Ano', 'Faixa_Etaria', 'Sexo', 'Estado_Civil', 'Cor_Raca', 'Nacionalidade', 'Situacao_Conclusao_EM', 'Ano_Conclusao_EM', 'Tipo_Escola', 'Tipo_Ensino', 'Treineiro', 'Cod_Municipio_Escola', 'Nome_Municipio_Escola', 'Cod_UF_Escola', 'UF_Escola', 'Dependencia_Adm_Escola', 'Localizacao_Escola', 'Situacao_Funcionamento_Escola', 'Cod_Municipio_Prova', 'Nome_Municipio_Prova', 'Cod_UF_Prova', 'UF_Prova', 'Presenca_Ciencias_Natureza', 'Presenca_Ciencias_Humanas', 'Presenca_Linguagens', 'Presenca_Matematica', 'Cod_Prova_Ciencias_Natureza', 'Cod_Prova_Ciencias_Humanas', 'Cod_Prova_Linguagens', 'Cod_Prova_Matematica', 'Nota_Ciencias_Natureza', 'Nota_Ciencias_Humanas', 'Nota_Linguagens', 'Nota_Matematica', 'Respostas_Ciencias_Natureza', 'Respostas_Ciencias_Humanas', 'Respostas_Linguagens', 'Respostas_Matematica', 'Lingua_Estrangeira', 'Gabarito_Ciencias_Natureza', 'Gabarito_Ciencias_Humanas', 'Gabarito_Linguagens', 'Gabarito_Matematica', 'Status_Redacao', 'Nota_Redacao_Comp1', 'Nota_Redacao_Comp2', 'Nota_Redacao_Comp3', 'Nota_Redacao_Comp4', 'Nota_Redacao_Comp5', 'Nota_Redacao', 'Q01_Escolaridade_Pai', 'Q02_Escolaridade_Mae', 'Q03_Ocupacao_Pai', 'Q04_Ocupacao_Mae', 'Q05_Pessoas_Residencia', 'Q06_Renda_Familiar', 'Q07_Empregado_Domestico', 'Q08_Banheiro', 'Q09_Quarto', 'Q10_Carro', 'Q11_Moto', 'Q12_Geladeira', 'Q13_Freezer', 'Q14_Maquina_Lavar', 'Q15_Maquina_Secar', 'Q16_Micro_Ondas', 'Q17_Maquina_Lavar_Louca', 'Q18_Aspirador_Po', 'Q19_TV_Cores', 'Q20_DVD', 'Q21_TV_Assinatura', 'Q22_Telefone_Fixo', 'Q23_Computador', 'Q24_Internet', 'Q25_Celular']

## 4. Exportação dos dados tratados

In [19]:
PROCESSED_PATH = r'..\data\processed\enem_2020_tratado.parquet'
df.to_parquet(PROCESSED_PATH, index=False)
print(f'Dados exportados para {PROCESSED_PATH}')
print(f'Shape: {df.shape}')

Dados exportados para ..\data\processed\enem_2020_tratado.parquet
Shape: (5783109, 76)